# Generated by Django 5.1.2 on 2024-11-05 20:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("problemy", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="problem",
            name="max_score",
            field=models.FloatField(default=20),
        ),
        migrations.AddField(
            model_name="submit",
            name="file",
            field=models.FileField(blank=True, upload_to=""),
        ),
    ]
