# Generated by Django 5.1.2 on 2024-11-12 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problemy", "0002_problem_max_score_submit_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problem",
            name="problem_set",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="problems",
                to="problemy.problemset",
            ),
        ),
    ]
