# Generated by Django 5.1.2 on 2024-12-04 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("problems", "0001_initial"),
        ("submits", "0001_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="filesubmit",
            name="enrollment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.enrollment"
            ),
        ),
        migrations.AddField(
            model_name="filesubmit",
            name="problem",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="problems.problem"
            ),
        ),
        migrations.AddField(
            model_name="filesubmit",
            name="scored_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="judgesubmit",
            name="enrollment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.enrollment"
            ),
        ),
        migrations.AddField(
            model_name="judgesubmit",
            name="problem",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="problems.problem"
            ),
        ),
        migrations.AddField(
            model_name="judgesubmit",
            name="scored_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="textsubmit",
            name="enrollment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.enrollment"
            ),
        ),
        migrations.AddField(
            model_name="textsubmit",
            name="problem",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="problems.problem"
            ),
        ),
        migrations.AddField(
            model_name="textsubmit",
            name="scored_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
