# Generated by Django 5.1.2 on 2024-12-07 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import seminare.submits.models


class Migration(migrations.Migration):
    dependencies = [
        ("submits", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="filesubmit",
            name="comment_file",
            field=models.FileField(
                blank=True, upload_to=seminare.submits.models.submit_file_filepath
            ),
        ),
        migrations.AlterField(
            model_name="filesubmit",
            name="scored_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="judgesubmit",
            name="scored_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="textsubmit",
            name="scored_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
