# Generated by Django 5.2.5 on 2026-04-15 12:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submits", "0003_alter_filesubmit_scored_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="filesubmit",
            name="late_accepted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="judgesubmit",
            name="late_accepted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="textsubmit",
            name="late_accepted",
            field=models.BooleanField(default=False),
        ),
    ]
