# Generated by Django 5.1.4 on 2025-05-04 16:55

from django.db import migrations, models

import seminare.submits.models


class Migration(migrations.Migration):
    dependencies = [
        ("submits", "0004_alter_filesubmit_options_alter_judgesubmit_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="judgesubmit",
            name="program",
            field=models.FileField(
                upload_to=seminare.submits.models.submit_judge_filepath
            ),
        ),
    ]
