# Generated by Django 5.2.5 on 2026-02-06 20:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contestrole",
            name="role",
            field=models.IntegerField(
                choices=[(1, "Organizátor"), (2, "Administrátor")]
            ),
        ),
    ]
