# Generated by Django 5.1.2 on 2024-12-08 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contests", "0002_category"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrollment",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="contests.category"
            ),
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
