# Generated by Django 5.2.5 on 2026-06-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contests", "0003_contest_iam_group"),
        ("users", "0002_alter_contestrole_role"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="contestrole",
            constraint=models.UniqueConstraint(
                fields=("user", "contest"), name="contestrole_unique__user_contest"
            ),
        ),
    ]
