# Generated by Django 5.2.17 on 2026-09-11 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_contestrole_contestrole_unique__user_contest"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="current_school_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
