# Generated by Django 5.2.17 on 2026-09-30 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_notification_notificationpreferences'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ('-created_at',)},
        ),
    ]
