# Generated by Django 5.1.4 on 2025-04-29 20:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_contestrole"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="enrollment",
            name="category",
        ),
    ]
