# Generated by Django 5.1.4 on 2025-08-04 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_remove_enrollment_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="current_grade",
            field=models.CharField(
                blank=True,
                choices=[
                    ("YNG", "<5zš"),
                    ("5ZS", "5zš"),
                    ("6ZS", "6zš"),
                    ("7ZS", "7zš"),
                    ("8ZS", "8zš"),
                    ("9ZS", "9zš"),
                    ("1SS", "1"),
                    ("2SS", "2"),
                    ("3SS", "3"),
                    ("4SS", "4"),
                    ("5SS", "5"),
                    ("OLD", "∞"),
                ],
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="current_school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.school",
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="grade",
            field=models.CharField(
                choices=[
                    ("YNG", "<5zš"),
                    ("5ZS", "5zš"),
                    ("6ZS", "6zš"),
                    ("7ZS", "7zš"),
                    ("8ZS", "8zš"),
                    ("9ZS", "9zš"),
                    ("1SS", "1"),
                    ("2SS", "2"),
                    ("3SS", "3"),
                    ("4SS", "4"),
                    ("5SS", "5"),
                    ("OLD", "∞"),
                ],
                max_length=3,
            ),
        ),
    ]
