# Generated by Django 5.1.4 on 2025-08-24 09:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_user_current_grade_user_current_school_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="school",
            name="edu_id",
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
    ]
