# Generated by Django 5.2.15 on 2026-07-27 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("camps", "0001_squashed_0002_camp_is_finalized"),
        ("problems", "0006_problem_external_points_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="camp",
            name="problem_set",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="camps",
                to="problems.problemset",
            ),
        ),
    ]
