# Generated by Django 5.1.4 on 2025-08-06 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contests", "0005_alter_contest_options_remove_contest_order"),
        ("problems", "0011_alter_problemset_end_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OldProblem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_problem_id", models.IntegerField()),
                (
                    "contest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contests.contest",
                    ),
                ),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="problems.problem",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        models.F("contest"),
                        models.F("old_problem_id"),
                        name="oldproblem_contest_problem_unique",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="OldRound",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_round_id", models.IntegerField()),
                (
                    "contest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contests.contest",
                    ),
                ),
                (
                    "problem_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="problems.problemset",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        models.F("contest"),
                        models.F("old_round_id"),
                        name="oldround_contest_round_unique",
                    )
                ],
            },
        ),
    ]
