# Generated by Django 5.1.4 on 2025-09-23 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("content", "0001_initial"),
        ("contests", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="menugroup",
            name="contest",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="contests.contest"
            ),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="content.menugroup"
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="contest",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="contests.contest"
            ),
        ),
    ]
