# Generated by Django 5.2.5 on 2026-01-30 14:08

from django.db import migrations, models

import seminare.content.models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="slug",
            field=models.CharField(
                max_length=256, validators=[seminare.content.models.path_validator]
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(max_length=256, unique=True),
        ),
    ]
