# Generated by Django 5.1.4 on 2025-07-22 15:30

from django.db import migrations, models

import seminare.content.models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0005_alter_page_options_remove_page_page__unique_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="slug",
            field=models.CharField(
                max_length=256,
                unique=True,
                validators=[seminare.content.models.path_validator],
            ),
        ),
    ]
