# Generated by Django 5.1.4 on 2025-08-04 09:52

from django.db import migrations, models
from django.utils.text import slugify


def add_slug_field(apps, schema_editor):
    Post = apps.get_model("content", "Post")
    for post in Post.objects.all():
        post.slug = slugify(post.title)
        post.save()


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0006_alter_page_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="slug",
            field=models.CharField(blank=True),
        ),
        migrations.RunPython(add_slug_field, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(),
        ),
    ]
