# Generated by Django 5.2.5 on 2026-02-11 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("problems", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="problem",
            name="points_publicly_visible",
            field=models.BooleanField(default=True),
        ),
    ]
