# Generated by Django 5.2.5 on 2026-02-16 10:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("problems", "0002_problem_points_publicly_visible"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problem",
            name="points_publicly_visible",
            field=models.BooleanField(default=False),
        ),
    ]
