# Generated by Django 5.1.2 on 2024-12-08 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problems", "0003_alter_problemset_contest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problem",
            name="problem_set",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="problems",
                to="problems.problemset",
            ),
        ),
        migrations.AlterField(
            model_name="text",
            name="problem",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="text_set",
                to="problems.problem",
            ),
        ),
        migrations.AlterField(
            model_name="text",
            name="type",
            field=models.CharField(
                choices=[
                    ("PS", "Problem statement"),
                    ("ES", "Example solution"),
                    ("SSH", "Susi small hint"),
                    ("SLH", "Susi large hint"),
                ],
                max_length=3,
            ),
        ),
    ]
