# Generated by Django 5.2.5 on 2026-04-15 11:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("problems", "0004_problem_reviewer"),
    ]

    operations = [
        migrations.AddField(
            model_name="problemset",
            name="solutions_public",
            field=models.BooleanField(default=True),
        ),
    ]
