# Generated by Django 5.2.5 on 2026-05-28 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("problems", "0005_problemset_solutions_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="problem",
            name="external_points",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="problem",
            name="external_submit_secret",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="problem",
            name="external_submit_url",
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
