# Generated by Django 5.1.4 on 2024-12-27 21:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("problems", "0005_problemset_is_public_text_text__unique_problem_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problemset",
            name="name",
            field=models.CharField(max_length=256),
        ),
    ]
