# Generated by Django 5.1.4 on 2025-04-28 17:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("problems", "0006_alter_problemset_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="problem",
            name="accepted_submit_types",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[("file", "File"), ("judge", "Judge"), ("text", "Text")]
                ),
                default=list,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="problem",
            name="judge_namespace",
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name="problem",
            name="judge_task",
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name="problem",
            name="text_answer",
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name="problem",
            name="accepted_submit_types",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("file", "File submit"),
                        ("judge", "Judge submit"),
                        ("text", "Text submit"),
                    ]
                ),
                default=list,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="problem",
            name="file_points",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="problem",
            name="judge_points",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="problem",
            name="text_points",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
