# Generated by Django 5.2.15 on 2026-09-06 12:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("problems", "0006_problem_external_points_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problem",
            name="external_submit_url",
            field=models.URLField(blank=True, max_length=256),
        ),
    ]
