# Generated by Django 5.1.4 on 2025-07-08 12:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("problems", "0008_problemset_rule_engine"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="problem",
            name="accepted_submit_types",
        ),
    ]
