# Generated by Django 5.1.4 on 2025-07-22 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("problems", "0009_remove_problem_accepted_submit_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="problemset",
            name="rule_engine_options",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
