# Generated by Django 5.1.4 on 2025-07-24 19:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("problems", "0010_problemset_rule_engine_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problemset",
            name="end_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="problemset",
            name="start_date",
            field=models.DateTimeField(),
        ),
    ]
