# Generated by Django 5.1.4 on 2025-08-06 18:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("problems", "0011_alter_problemset_end_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="problemset",
            name="slug",
            field=models.SlugField(blank=True, max_length=64),
        ),
    ]
