# Generated by Django 5.1.4 on 2025-08-06 18:55

from django.db import migrations


def set_problemset_slugs(apps, schema_editor):
    ProblemSet = apps.get_model("problems", "ProblemSet")
    for problem_set in ProblemSet.objects.all():
        problem_set.slug = str(problem_set.id)
        problem_set.save()


def unset_problemset_slugs(apps, schema_editor):
    ProblemSet = apps.get_model("problems", "ProblemSet")
    for problem_set in ProblemSet.objects.all():
        problem_set.slug = ""
        problem_set.save()


class Migration(migrations.Migration):
    dependencies = [
        ("problems", "0012_problemset_slug"),
    ]

    operations = [
        migrations.RunPython(
            code=set_problemset_slugs,
            reverse_code=unset_problemset_slugs,
        ),
    ]
