# Generated by Django 5.1.4 on 2025-08-06 19:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("problems", "0013_auto_20250806_2055"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problemset",
            name="slug",
            field=models.SlugField(max_length=64, unique=True),
        ),
    ]
