# Generated by Django 5.1.4 on 2025-08-10 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0005_alter_contest_options_remove_contest_order'),
        ('problems', '0014_alter_problemset_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemset',
            name='slug',
            field=models.SlugField(max_length=64),
        ),
        migrations.AddConstraint(
            model_name='problemset',
            constraint=models.UniqueConstraint(models.F('contest'), models.F('slug'), name='problemset__contest_slug__unique'),
        ),
    ]
