# Generated by Django 5.1.4 on 2025-08-11 08:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("problems", "0015_alter_problemset_slug_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="problem",
            constraint=models.UniqueConstraint(
                models.F("problem_set"),
                models.F("number"),
                name="problem__problem_set_number__unique",
            ),
        ),
    ]
