# Generated by Django 5.1.4 on 2025-08-20 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("problems", "0016_problem_problem__problem_set_number__unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="problemset",
            name="is_finalized",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="ProblemSetFrozenResults",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("table", models.CharField(max_length=64)),
                ("data", models.JSONField(blank=True, default=dict)),
                (
                    "problem_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="problems.problemset",
                    ),
                ),
            ],
            options={
                "unique_together": {("problem_set", "table")},
            },
        ),
    ]
