# Generated by Django 5.1.4 on 2025-08-31 07:32

import pathlib

import django.core.files.storage
from django.db import migrations, models

import seminare.problems.models


class Migration(migrations.Migration):
    dependencies = [
        ("problems", "0017_problemset_finalized_problemsetfrozenresults"),
    ]

    operations = [
        migrations.AddField(
            model_name="problemset",
            name="solution_pdf",
            field=models.FileField(
                blank=True,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(
                    location=pathlib.PurePosixPath("/app/private")
                ),
                upload_to=seminare.problems.models.get_solution_filename,
            ),
        ),
        migrations.AddField(
            model_name="problemset",
            name="statement_pdf",
            field=models.FileField(
                blank=True,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(
                    location=pathlib.PurePosixPath("/app/private")
                ),
                upload_to=seminare.problems.models.get_statement_filename,
            ),
        ),
    ]
