# Generated by Django 5.1.4 on 2025-04-29 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0002_category'),
        ('users', '0007_remove_enrollment_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
