# Generated by Django 5.2.5 on 2026-06-20 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contests", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contest",
            name="iam_group",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
