# Generated by Django 5.1.4 on 2025-07-07 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contests", "0003_delete_category"),
        ("sites", "0002_alter_domain_unique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contest",
            name="site",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="sites.site"
            ),
        ),
    ]
