# Generated by Django 5.1.4 on 2025-07-07 13:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contests", "0004_alter_contest_site"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contest",
            options={},
        ),
        migrations.RemoveField(
            model_name="contest",
            name="order",
        ),
    ]
