# Generated by Django 5.1.4 on 2025-08-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contests", "0006_ruledata"),
    ]

    operations = [
        migrations.AddField(
            model_name="ruledata",
            name="key",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
    ]
