# Generated by Django 5.1.4 on 2025-08-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contests", "0007_ruledata_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="contest",
            name="contact_email",
            field=models.EmailField(default="info@trojsten.sk", max_length=254),
            preserve_default=False,
        ),
    ]
